version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: project_task_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/project_task_db
      - REDIS_URL=redis://redis:6379/0

  celery:
    build: .
    command: celery -A project_task_manager worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/project_task_db
      - REDIS_URL=redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A project_task_manager beat -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/project_task_db
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
